Purhase model
ssunivs/New-ssunivs-store pull request #8
Opened 2022-01-04 13:19 UTC by makemyway-kr

table 이름, relationship 수정사항 반영.

2022-01-04 13:19 UTC, makemyway-kr reviewed
수정사항 반영해서 해봤어요
sqlalchemy.orm.relationship이어서 db.orm.relationship으로 했는데 이게 맞죠?

2022-01-04 14:10 UTC, clroot requested changes
## order 모델
- customer > user로 변경 및 relationship으로 변경 (relationship 설정하면, ORM 단에서 외래키로 생성해주고, 객체 조회시, 해당 외래키 참조하여 연관 테이블 조회해줌) > 별도 외래키 직접 관리할 필요 없다는 말
  - 그리고 연관관계 지정 시, 가급적 모델 이름 그대로 사용(한 모델에서 다른 모델을 여러번 참조할 경우에는 이름을 구분해줄 필요가 있지만, 그렇지 않은 경우에는(특히 OneToOne, ManyToOne) 모델 이름 그대로 유지하였으면
- order_customer 멤버 삭제(위에서 customer를 user로 바꾸며 연관관계 지정하였기에 필요없음)
- total_price 는 값으로 테이블에 저장하지 않고, get_total_price 메서드 생성하여, 그 때 그 때 계산할 수 있도록
- order_detail > order_goods_list 로 변경 & ManyToOne 으로 연관관계 지정
  - 한개 주문에 대해서, 여러 종류의 상품을 구입할 수 있으니
- 배송 관련 정보 굳이 다른 테이블로 분리하고 싶은 이유는 무엇인지?
  - Order 모델의 값이 테이블을 쪼갤정도로 방대하지 않은 것 같음
  - 테이블 쪼갤 경우, 오히려 나중에 조회 시, JOIN을 위한 추가 연산이 필요함 > 아직 쪼갤 필요성은 안보임
  - 배송 관련 값을 주소(Address) 클래스로 묶어서 Composite Column 으로 사용하면 좋겠음
  - user 모델에도 Adress를 Composite로 넣어서, 기본 배송지로 저장하고
  - order 모델에도 Composite 컬럼으로 넣어서 사용하면 좋을 듯
- order.status
  - ChoiceType을 사용하여 무결성을 유지하려는 의도는 좋으나
  - order.status 같은 값은 모델 바깥 쪽에서 참조할 일 많음
  - Enum 타입을 사용하여, 무결성을 유지 + 모델 바깥 쪽에서도 해당 상수들을 이용할 수 있도록 개선하면 좋을 것 같음

## order_details 모델
- 일단 이름을 order_goods 또는 order_item으로 변경할 것(order_itme으로 변경 시, goods 모델도 item으로 변경)
  - 이 모델은 주문에 들어있는 상품에 대한 정보를 기록하기에
  - detail이라는 모호한 표현을 사용하지 않고, goods 또는 item 으로 명시적으로 표현해줄 것
- purchase_number > order 로 변경 & relationship 지정(ManyToOne이 되게끔)
  - 왜? 하나의 주문에 여러가지 상품이 있을 수 있으니
- goods 또한 ForeignKey 직접 관리하는 것이 아니라, relationship 사용하여 관리하도록
- 그리고 별도 파일로 분리하여 모델 생성하였으면
  - 가급적 하나의 파일에 하나의 클래스가 정의되었으면 좋겠음

2022-01-04 14:16 UTC, makemyway-kr commented
total price변수는 그대로 두고 메소드로 계산해서 주문 관련 변동사항 있으면 넣게하면 어떤가요 매번 띄워줄때마다 계산하면 그것도 그것대로 낭비인듯해서

2022-01-04 14:17 UTC, clroot commented
주문-상품이 변경될 때마다 DB에 다시 기록을 해주는 비용보다
실시간으로 계산해주는 비용이 전체적으로 적음

쓰기 비용 > 조회 비용

2022-01-04 16:09 UTC, makemyway-kr reviewed
total price method제외하고는 일단 수정했습니다.
purchase_goods는 종속적인 테이블이라서(multivalued) 그대로 뒀어요
address를 composite으로 하는것은 차후 users테이블이랑 같이 해볼께요

2022-01-04 16:27 UTC, clroot commented
total-price 메서드로 구현하는 것이 전체적으로 훨씬 효율적인 이유를 좀 더 디테일하게 말하자면

DB에서 필드 하나를 업데이트 하기 위해서는
먼저 인덱스로 해당 row를 찾고, 디스크에 액세스해서 값을 바꿔줘야하고
+ 주문에 포함된 상품이 변경될 때마다 이를 계산하고 업데이트 하는 로직을 구현해야 하지만

메서드로 조회할 경우에는
select 해온 뒤, 파이썬 단에서 그냥 sum 연산만 하면 끝나요.
게다가 주문에 포함된 상품의 변화에 따른 총 가격의 변화를 신경 쓸 필요도 없고.
(장바구니에 넣고 빼는 모든 순간마다, 해당 값을 다시 계산해서 update 쿼리를 날려야해요)


지속적으로 통계를 내며, 시간대별로 기록이 필요한 값이라면
번거롭더라도 DB에 별도로 기록을 하는 것이 맞지만,
주문의 총 가격은 이정도로 기록을 할 필요가 없는 데이터이기에

쓰기 비용보다 읽기 비용이 저렴한 점,
코드에서 신경써야 할 부분이 감소하는 점

이 두 이유로 값을 테이블에 저장하는 것이 아닌
메서드로 구현하는 것을 권장함

2022-01-05 03:28 UTC, makemyway-kr commented
수정안한다는게 아녔어요...! 저도 그렇게 하는게 낫겠네 싶어서 오늘내일 하려 한겁니당...

2022-01-06 04:19 UTC, makemyway-kr reviewed
total price까지 추가했습니당
@clroot

2022-01-07 06:18 UTC, clroot requested changes
# app/models/order.py
- order_goods 모듈 분리하기
- order_goods.purchase_number > order_goods.order 로 변경하기
  - purchase_number 는 id 를 가르키는 것이 아닌, sqlalchemy의 기능으로인해 order 객체가 참조되기에, purchase_number 라는 이름은 적절하지 않음
  - 추가적으로 외래키를 참조하는 변수명은, 외래키가 가르키는 모델 이름 + id 형식을 준수할 것!(ex. order_id)

  # app/models/user.py
- User.users_order > User.order_list 로 이름 변경
  - 유저의 주문이 여러개일 수 있으니, 위 이름이 더 적절해보임

2022-01-07 06:33 UTC, makemyway-kr commented
@clroot order_goods는 order에 종속적이기 때문에 따로 분리하지 않는게 나중에 더 편할 것 같아 분리 안하는게 나을듯합니다.

2022-01-07 06:35 UTC, clroot commented
하나의 파일에 하나의 클래스만 있는 것이 더 좋다고 생각하지만
그렇게 생각하면 그렇게 ㄱㄱ

2022-01-07 06:54 UTC, makemyway-kr reviewed
@clroot 수정사항 완료~

2022-01-07 07:01 UTC, clroot approved these changes

2022-01-07 07:02 UTC, merged